### ISSUE TITLE
Library hangs after second http error 500

### ISSUE THREAD

**Issue by thl-mot** [mirthas/FritzTR064#1]
I basically followed the example of listing all wlan devices.
My Fritzbox (FRITZ!Box Fon WLAN 7390) returns me 8 "NewTotalAssociations".
When going through thes Assocuations I get the following results:
1. HTTP 500 internal Error of the box
2. one valid DeviceInfo
3. one second valid DeviceInfo
4. HTTP 500 internal Error of the box
5. my application hangs

after debugging into it, I found out that in the class FritzConnection the process hangs in the function getSOAPXMLIS at the line "CloseableHttpResponse response = httpClient.execute(targetHost, httppost, context);"
it never returns from this line.

I am using httpcomponent-client-4.4.1

**Comment by thl-mot** [comment]
Ok, after digging into the sourcecode of the library I may hav found the bug.
It's in the method FritzConnection.getSOAPXMLIS( ... )
After running into the Server Error (in my case HTTP Error 500). A IOException is thrown. The number of Responses may be limited so, when just throwing the exception the response is still cept somewhere in a (limited) pool in the http-library. 
I resolved my problem of never returning from httpClient.execute by changing the code in the if block to:
```
	  if (response.getStatusLine().getStatusCode()!=200){
		  response.close();
		  throw new IOException(response.getStatusLine().toString());
	  }
```
I don't know if this really solves the problem, but it may be a hint.

**Comment by mirthas** [comment]
You were right. There was a problem with some resource management. Ill hope it is fixed now. Thank you for your issue report.
