### ISSUE TITLE
try the tool in a non fritz modem

### ISSUE THREAD

**Issue by ehabtanta** [mirthas/FritzTR064#2]
i need a tr064 client to deal with my router but i was unable to get any 

so i disparately need your help to modify your tool so it works with my router  

the router ip :192.168.1.1
the upnp port :37215 
the upnp file :https://www.dropbox.com/s/r62lw3dxkska8h2/upnpdev.xml?dl=0
its location in the router :http://192.168.1.1:37215/upnpdev.xml
the tr064 file: https://www.dropbox.com/s/bnlh3vt9qlo7zc8/right%20tr064dev.xml?dl=0
its location in the router : http://192.168.1.1:37215/tr064dev.xml
the desc file of the service i want to deal with : https://www.dropbox.com/home?preview=UserItf.xml
its location in the router :   http://192.168.1.1:37215/desc/UserItf.xml

the soap actions that i want to deal with from the UserItf.xml  are :
<name>GetLoginUsername</name>
<name>GetLoginPassword</name>

the default tr064 digest auth is required with the following data 
username:"dslf-config"
password: admin
realm :HuaweiHomeGateway
qop:auth

so can u please help me

**Comment by mirthas** [comment]
Did you try to change the appropriated Lines in FritzConnection.java? Should be Line 66-68 and  109-113

**Comment by ehabtanta** [comment]
will try and report back 
thanks alot

**Comment by ehabtanta** [comment]
sorry for being so noob but how to execute the .java files using the http client ?

**Comment by mirthas** [comment]
Ill probably make a own branch  for this
